version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ticketera_db
    restart: always
    environment:
      POSTGRES_USER: ticketera_user
      POSTGRES_PASSWORD: ticketera_pass_dev
      POSTGRES_DB: ticketera_dev
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ticketera_net

  redis:
    image: redis:7-alpine
    container_name: ticketera_redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - ticketera_net

networks:
  ticketera_net:
    driver: bridge

volumes:
  pgdata:
